#Set custom prefix
set -ga terminal-overrides ",*256col*:Tc"
#set-option -sa terminal-overrides ",xterm*:Tc"
#set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-space
bind C-space send-prefix
bind-key -n M-l send-keys 'C-l' # ---> alt+l to clear screen
bind -n M-H previous-window
bind -n M-L next-window

set-option -g default-command /bin/fish
set-option -g default-shell /bin/fish
set-option -g @tmux-autoreload-configs '$HOME/.config/tmux/tmux.conf'

#set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default ---> To remain in copy mode
set -g @yank_selection_mouse 'clipboard'
set -g @yank_selection 'clipboard' # or 'secondary' or 'clipboard'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on
#setw -g mode-mouse off
set -g set-clipboard on
#set -s set-clipboard external
#set -s set-clipboard off
#set -g @yank_action 'copy-pipe-no-clear'
#bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
#bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#splits and new windows to have the current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"


# CATPPUCCIN CONFIG


##set -g @catppuccin_flavour 'macchiato'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set-option -g @plugin 'b0o/tmux-autoreload'

run '~/.config/tmux/plugins/tpm/tpm'
