#Set custom prefix
set -ga terminal-overrides ",*256col*:Tc"
#set-option -sa terminal-overrides ",xterm*:Tc"
#set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
unbind C-b
set -g prefix C-space
bind C-space send-prefix

#set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default
set-option -g default-command /bin/fish
set-option -g default-shell /bin/fish
set-option -g @tmux-autoreload-configs '/home/cr33p3r/.config/tmux/tmux.conf'
#unbind C-l
#bind-key -n M-l send-keys -R M-l  
#bind-key M-l send-keys "clear" \; send-keys "Enter"
#bind-key -n M-l send-keys M-l \; send-keys -R
bind-key -n M-l send-keys -R M-l
set -g @yank_selection_mouse 'clipboard'
set -g @yank_selection 'clipboard' # or 'secondary' or 'clipboard'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on
#setw -g mode-mouse off
set -g set-clipboard on
#set -s set-clipboard external
#set -s set-clipboard off
#set -g @yank_action 'copy-pipe-no-clear'
#bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
#bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

set -g @catppuccin_flavour 'macchiato'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-copycat'
set-option -g @plugin 'b0o/tmux-autoreload'


run '~/.config/tmux/plugins/tpm/tpm'
