#Set custom prefix
set-option -sa terminal-overrides ",xterm*:Tc"
unbind C-b
set -g prefix C-space
bind C-space send-prefix

#set-option -g default-command /bin/fish
#set-option -g default-shell /bin/fish
#unbind C-l
#bind-key -n C-l send-keys -R C-l \;  
set -g @yank_selection_mouse 'clipboard'
set -g @yank_selection 'clipboard' # or 'secondary' or 'clipboard'

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g mouse on
#setw -g mode-mouse off
set -g set-clipboard on
#set -s set-clipboard external
#set -s set-clipboard off
#set -g @yank_action 'copy-pipe-no-clear'
#bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
#bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

set -g @catppuccin_flavour 'macchiato'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
